FROM tomcat:9
MAINTAINER xyz
RUN ls -l
# COPY if_file_exists.sh .
# ADD /target/if_file_exist.sh .
# RUN rm -rf /usr/local/tomcat/webapps/*
# RUN [“rm”, “-fr”, “/usr/local/tomcat/webapps/ROOT”]
# COPY ./DockerExample.war /usr/local/tomcat/webapps/ROOT.war

# CMD [“catalina.sh”, “run”] 
